repositories:
    - name: dts
      url: https://helm.dts-stn.com
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: openfiscacanada
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/openfisca-canada-dts@helm/charts?ref=main
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 

releases:
# OPEN FISCA CANADA
  - name: openfiscacanada-{{ .Environment.Name }}
    chart: openfiscacanada/openfiscacanada
    version: 0.0.3
    values:
      - overrides/openfiscacanada.yaml.gotmpl
    labels:
        category: dts
        app: openfiscacanada
        tier: server
    namespace: openfiscacanada-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
