name: Running Tests

on: pull_request
jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
        - name: 'Docker Action'
          uses: addnab/docker-run-action@v1
          with:
            image: DockerFile
            run: echo "hello world"

