# name: Lint and Test

# on: pull_request

# jobs:
#   test:
#     name: Test on node 12 and ubuntu-latest
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1      
      
#       - name: Use node 12
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org      

#       - name: install
#         run: npm install      

#       - name: lint
#         run: npm run lint      

#       - name: build
#         run: npm run build      

#       - name: unit test
#         run: npm test
