name: Running Tests

on: pull_request
jobs:
  Tests:
    name: 'Open Fisca Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Docker Build and Run Tests'
        run: |
          docker build -t .
          docker exec openfisca test -c openfisca_canada openfisca_canada/tests

