name: Running Tests

on: pull_request
jobs:
  Tests:
    name: 'Open Fisca Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Docker Build and Run Test'
        run: |
          docker build -t testimage .
          docker run -d -it -p 5000:5000 --name testcontainer testimage
          docker exec testimage openfisca test -c openfisca_canada openfisca_canada/tests          

